# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-15 19:12
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, error_messages={'unique': '该用户名已经存在'}, max_length=40, unique=True, verbose_name='用户名')),
                ('image', models.ImageField(default='img/default_user.jpg', upload_to=accounts.models.reset_user_image, verbose_name='图像')),
                ('email', models.EmailField(error_messages={'unique': '该邮箱已经存在'}, max_length=255, unique=True, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=False, verbose_name='状态')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='管理员')),
                ('nickname', models.CharField(blank=True, max_length=64, null=True, verbose_name='昵称')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.CreateModel(
            name='PermissionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='权限名称')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': '权限管理',
                'verbose_name_plural': '权限管理',
            },
        ),
        migrations.CreateModel(
            name='RoleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色名称')),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.PermissionList', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色管理',
                'verbose_name_plural': '角色管理',
            },
        ),
        migrations.AlterUniqueTogether(
            name='permissionlist',
            unique_together=set([('name', 'url')]),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.RoleList', verbose_name='角色'),
        ),
    ]
