# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-15 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('url', models.URLField(verbose_name='网址')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('c_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '站点导航',
                'verbose_name_plural': '站点导航',
            },
        ),
        migrations.AlterUniqueTogether(
            name='navstore',
            unique_together=set([('name', 'url')]),
        ),
    ]
